CFLAGS += -I ../userspace/libc/include/

include ../userspace/libc/makefile
include ../userspace/app/helloworld/makefile
include ../userspace/app/terminal/makefile
include ../userspace/guard/makefile
